### ISSUE TITLE
listAllDrivesWithHttpInfo function fails to catch and null response exception 

### ISSUE THREAD

**Issue by S-Panta** [owncloud/libre-graph-api-php#4] opened 2023-10-18 06:14 UTC
If the URL is in the wrong format, `response` would be  `null` and this function doesn't throw any exception but returns `null`. `response` as `null` makes no sense. Thus the function should handle this exception.

Note: I have used `[ocis-php-sdk]` to reproduce the error.
https://github.com/owncloud/ocis-php-sdk 

## Steps to reproduce
Create an Ocis object using the service Url with an extra slash in it and an access token. 
```php
$ocis = new Ocis('https://example.ocis.com/', $accessToken);
```
The response will be returned as `null`.

## Expected result
The function should handle the error.

**Comment by individual-it** [comment] 2023-10-20 06:01
The problem here is if the server returns a `200` response but the content is not JSON decodeble e.g. in https://github.com/owncloud/libre-graph-api-php/blob/main/lib/Api/MeDrivesApi.php#L203
`json_decode` returns `null` in that case and that is propagated upwards

**Comment by individual-it** [comment] 2023-10-20 08:14
should be fixed by https://github.com/OpenAPITools/openapi-generator/pull/16879

**Comment by individual-it** [comment] 2023-11-23 10:11
@S-Panta please retest, and check if the issue is fixed

**Comment by S-Panta** [comment] 2023-11-24 09:01
Somehow, the body of the `response` of `listAllDrivesWithHttpInfo()` function is giving html as body response when the wrong format of URL is provided.  Json can't decode that response body and it returns null as it's output.  I am not if the issue is fixed. It stills give back null response.

**Comment by individual-it** [comment] 2023-11-24 09:09
@S-Panta exactly and in the current version of this library (after https://github.com/OpenAPITools/openapi-generator/pull/16879) the function should not return `null` but throw an `JsonException` when it cannot decode the output.
Do you run the most recent version of this library? Please check your package.json , what version of `libre-graph-api-php` are you using? maybe rerun `composer update`?

**Comment by S-Panta** [comment] 2023-11-24 11:05
I used the latest generation and the response is still `Null`.

**Comment by amrita-shrestha** [comment] 2023-11-27 04:30
> I used the latest generation and the response is still `Null`.

The current image doesn't include fixed PR. I made bump PR : https://github.com/owncloud/libre-graph-api/pull/143
After this Pr merge you can try

**Comment by individual-it** [comment] 2023-11-29 10:02
The bump did not do anything, it did not produce any different output

**Comment by individual-it** [comment] 2023-11-29 10:14
the issue was that we haven't applied the fix of https://github.com/OpenAPITools/openapi-generator/pull/17120 in the template used in the generator, should be done by https://github.com/owncloud/libre-graph-api/pull/146

**Closed as completed** 2023-12-01 04:01 UTC
Labels: bug

**Comment by individual-it** [comment] 2023-12-01 04:02
@S-Panta please confirm if the issue is really fixed

**Comment by S-Panta** [comment] 2023-12-01 06:10
It is fixed.
